function circuitjs1(){var Q='bootstrap',R='begin',S='gwt.codesvr.circuitjs1=',T='gwt.codesvr=',U='circuitjs1',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='position:absolute; width:0; height:0; border:none; left: -1000px;',_=' top: -1000px;',ab='CSS1Compat',bb='<!doctype html>',cb='',db='<html><head><\/head><body><\/body><\/html>',eb='undefined',fb='readystatechange',gb=10,hb='Chrome',ib='eval("',jb='");',kb='script',lb='javascript',mb='moduleStartup',nb='moduleRequested',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='circuitjs1::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='circuitjs1.nocache.js',Jb='base',Kb='//',Lb='locale',Mb='en',Nb='locale=',Ob=7,Pb='&',Qb='__gwt_Locale',Rb='_',Sb='Unexpected exception in locale detection, using default: ',Tb=2,Ub='user.agent',Vb='webkit',Wb='safari',Xb='msie',Yb=11,Zb='ie10',$b=9,_b='ie9',ac=8,bc='ie8',cc='gecko',dc='gecko1_8',ec=3,fc=4,gc='selectingPermutation',hc='circuitjs1.devmode.js',ic='0000B6A21351413C42D832E312DD7965',jc='default',kc='7CAF1A67BAED9CD877A9D647C1947A3D',lc='7EBEC6AE4490BF3FE4BE547452C76366',mc='vi',nc='8B7985336DAFB21848343A32BD9C8E12',oc='95748C177079254764E3E1864EDD28A5',pc='9E355BB82593EE176166D30462C79429',qc='ABBFA7B48CE90F92EE1C166D20182BCE',rc='AFE4E87CCDD7881ADC0F18E22327025A',sc='B0F78B4CE9F305DC67FB67E493C16583',tc='BA7E9691E6E1EDE481F3CFFAD9EBED8A',uc='BE060D0AE91A9057A406B881D8A01F45',vc='BF7B24971CFC525D729E2ABDC75705DA',wc='C5D4B616606E11FB2342F15B1D3D6751',xc='DD412E6D606D2F00DDC973FED1291B59',yc='EC0DAF4565041A7F8F99581D63F6053C',zc=':',Ac='.cache.js',Bc='link',Cc='rel',Dc='stylesheet',Ec='href',Fc='loadExternalRefs',Gc='gwt/clean/clean.css',Hc='style.css',Ic='end',Jc='http:',Kc='file:',Lc='_gwt_dummy_',Mc='__gwtDevModeHook:circuitjs1',Nc='Ignoring non-whitelisted Dev Mode URL: ',Oc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
circuitjs1.__sendStats=t;circuitjs1.__moduleName=U;circuitjs1.__errFn=null;circuitjs1.__moduleBase=W;circuitjs1.__softPermutationId=X;circuitjs1.__computePropValue=null;circuitjs1.__getPropMap=null;circuitjs1.__installRunAsyncCode=function(){};circuitjs1.__gwtStartLoadingFragment=function(){return null};circuitjs1.__gwt_isKnownPropertyValue=function(){return false};circuitjs1.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};circuitjs1.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[circuitjs1.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.id=U;a.style.cssText=$+_;a.tabIndex=-1;r.body.appendChild(a);w=a.contentWindow.document;w.open();var b=document.compatMode==ab?bb:cb;w.write(b+db);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==eb){return typeof r.body!=eb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(r.removeEventListener){r.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(fb,d,false)}var e=setInterval(function(){d()},gb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(ib));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(jb));g=e.createElement(kb);g.language=lb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(kb);g.language=lb;g.text=c[i];f.appendChild(g);d(f,g)}}}
circuitjs1.onScriptDownloaded=function(a){l(function(){m(a)})};t(mb,nb);var n=r.createElement(kb);n.src=k;if(circuitjs1.__errFn){n.onerror=function(){circuitjs1.__errFn(U,new Error(ob+code))}}r.getElementsByTagName(pb)[X].appendChild(n)}
circuitjs1.__startLoadingFragment=function(a){return G(a)};circuitjs1.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(kb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(qb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,cb);if(j.indexOf(tb)>=X){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=cb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;circuitjs1.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=X?a.substring(X,d+Y):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return cb}
function h(){var a=r.getElementsByTagName(kb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return cb}
function i(){var a=r.getElementsByTagName(Jb);if(a.length>X){return a[a.length-Y].href}return cb}
function j(){var a=r.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return circuitjs1.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Lb]=function(){var b=null;var c=Mb;try{if(!b){var d=location.search;var e=d.indexOf(Nb);if(e>=X){var f=d.substring(e+Ob);var g=d.indexOf(Pb,e);if(g<X){g=d.length}b=d.substring(e+Ob,g)}}if(!b){b=__gwt_getMetaProperty(Lb)}if(!b){b=q[Qb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Lb,b)){var h=b.lastIndexOf(Rb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Sb+a)}q[Qb]=c;return b||Mb};l[Lb]={'default':X,'en':Y,'vi':Tb};m[Ub]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Vb)!=-1}())return Wb;if(function(){return a.indexOf(Xb)!=-1&&(b>=gb&&b<Yb)}())return Zb;if(function(){return a.indexOf(Xb)!=-1&&(b>=$b&&b<Yb)}())return _b;if(function(){return a.indexOf(Xb)!=-1&&(b>=ac&&b<Yb)}())return bc;if(function(){return a.indexOf(cc)!=-1||b>=Yb}())return dc;return cb};l[Ub]={'gecko1_8':X,'ie10':Y,'ie8':Tb,'ie9':ec,'safari':fc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};circuitjs1.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};circuitjs1.__computePropValue=n;q.__gwt_activeModules[U].bindings=circuitjs1.__getPropMap;t(Q,gc);if(s()){return G(hc)}var o;try{k([Mb,_b],ic);k([jc,bc],kc);k([jc,Zb],lc);k([mc,Wb],nc);k([Mb,Wb],oc);k([mc,dc],pc);k([mc,Zb],qc);k([Mb,Zb],rc);k([mc,bc],sc);k([jc,_b],tc);k([Mb,bc],uc);k([Mb,dc],vc);k([mc,_b],wc);k([jc,Wb],xc);k([jc,dc],yc);o=i[n(Lb)][n(Ub)];var p=o.indexOf(zc);if(p!=-1){j=parseInt(o.substring(p+Y),gb);o=o.substring(X,p)}}catch(a){}circuitjs1.__softPermutationId=j;return G(o+Ac)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Bc);b.setAttribute(Cc,Dc);b.setAttribute(Ec,G(a));r.getElementsByTagName(pb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Fc,R);c(Gc);c(Hc);t(Fc,Ic)}
D();circuitjs1.__moduleBase=F();v[U].moduleBase=circuitjs1.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Jc||q.location.protocol==Kc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Lc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Mc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Nc+N)}N=cb}if(N&&!q[M]){q[M]=true;q[M+Oc]=F();var O=r.createElement(kb);O.src=N;var P=r.getElementsByTagName(pb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Ic);C(J);return true}
circuitjs1.succeeded=circuitjs1();